version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: SkillSwapDB
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    env_file:
      - backend/.env
    volumes:
      - ./backend/src:/app/src
      - ./backend/public:/app/public
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - internal

volumes:
  pgdata:

networks:
  internal:
